### ISSUE TITLE
push demo site image to registry

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/demo-inveniordm#7]

**Comment by ppanero** [comment]
@zzacharo could you drop here how to to in GH, then we see and put also OpenShift?

**Comment by zzacharo** [comment]
After you have 

Pushing an image to Github requires the next steps:
- Create a public repository if you don't have one that you will push your package in github
- Create an access token in github. This access token must have read:packages and write:packages scopes. See how to create a token [here](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line).
- Now you need to build your image locally for your RDM instance following the below command
```
$ docker build -t  docker.pkg.github.com/<your-github-username>/<your-github-repo-name>/<image-name>:<version> <path-to-your-instance>
```
- Next you need to login with docker client to the github registry so you can push your new image.
```
docker login docker.pkg.github.com -u <YOU_GITHUB_USERNAME> -p <YOUR_GITHUB_TOKEN>
```
-  Then, last step is to push your package to the github registry. For doing that, run the below command:
```
docker push docker.pkg.github.com/<your-github-username>/<your-github-repo-name>/<image-name>:<version>

E.g  docker push docker.pkg.github.com/myuser/myrepo/myimage:latest
```
- After succesfully created the package in github you need to specify this image to your `values.yaml` file:
```
- web: docker.pkg.github.com/myuser/myrepo/myimage:latest
- worker: docker.pkg.github.com/myuser/myrepo/myimage:latest
```

Because github requires for now to be authenticated in order to pull your image, for being able to pull the image from openshift spefically you need to run:
```
$ oc create secret docker-registry <SECRET_NAME> --docker-server=docker.pkg.github.com --docker-username=<YOUR_GITHUB_USERNAME> --docker-password=<YOUR_GITHUB_PASSWORD>
$ oc secrets link default <SECRET_NAME> --for=pull --namespace=<YOUR_OPENSHIFT_PROJECT_NAME>
```

Eventually you can run the `helm install ...` command to install you RDM instance in openshift using github registry.
